### ISSUE TITLE
As developer I want a production ready system

### ISSUE THREAD

**Issue by Fischaela** [podcasterinnen/chosen-api#29]
# Todos

## More important
* [x] clone repo [chosen-api master branch](https://github.com/podcasterinnen/chosen-api) for [api.podcasterinnen.org](api.podcasterinnen.org)
* [x] clone repo [chosen-client master branch](https://github.com/podcasterinnen/chosen-client) for [podcasterinnen.org](podcasterinnen.org)
* [x] add production database for [api.podcasterinnen.org](api.podcasterinnen.org)
* [x] add `secrets.exs` file (see [apitest.podcasterinnen.org](apitest.podcasterinnen.org)) with 
  - `ChosenApiWeb.Endpoint` 
  - `ChosenApi.Repo`
  - `ChosenApi.Mailer`
* [ ] add automatic backups for production database
* [ ] add automatic backups for test database

## Less important
* [ ] do not log ip addresses
